# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8aa539a7c9577832d64c9b48958021d3f439671861122a8c21e6a63ea8b929d28f2d79d263bf205cbb069b3f095c7e707247da272cdd269bc71e6432940b08ea

test:
  secret_key_base: 2877747a948b7e46a65ec5d0ff7bf360c7ea58c3eab3249a93ae189314dad35cd4d19767c55d97e22adbe1f99d8d7588d32c50012f5656a26d8a12f63ae68d2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
